# Generated by Django 4.0.6 on 2022-07-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_branch_contractor_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.TextField()),
                ('external_number', models.TextField()),
                ('is_committed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.branch')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDocumentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mnemonic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.commonitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDocumentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_committed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=1)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vat_amount_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vat_amount_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchasedocument')),
            ],
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchasedocumentdefinition'),
        ),
    ]
