# Generated by Django 4.0.6 on 2022-07-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseitemexternalnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentposition',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseitem'),
        ),
    ]
