# Generated by Django 4.0.6 on 2022-07-19 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasedocumentposition_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='receive_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
