# Generated by Django 4.0.6 on 2022-07-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_contractorbranch'),
        ('purchases', '0004_purchasedocument_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='contractor_div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.contractorbranch'),
        ),
    ]
