# Generated by Django 4.0.6 on 2022-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchasedocument_contractor_div'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocumentposition',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentposition',
            name='gross_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentposition',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentposition',
            name='net_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentposition',
            name='vat_amount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentposition',
            name='vat_amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
