# Generated by Django 4.0.6 on 2022-07-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_contractor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitem',
            name='type_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.itemtype'),
        ),
    ]
