# Generated by Django 4.0.6 on 2022-07-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_commonitem_type_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.contractor')),
            ],
        ),
    ]
