# Generated by Django 4.0.6 on 2022-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_contractorbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonitem',
            name='SKU',
            field=models.TextField(blank=True, null=True),
        ),
    ]
