# Generated by Django 4.0.6 on 2022-07-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_commonitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='full_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commonitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.itemcategory'),
        ),
    ]
